// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/search-players.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
var API = "https://api.msmc.cc/api/fc26";
var search_players_default = defineTool({
  name: "search_players",
  title: "Search players",
  description: "Search EA Sports FC 26 players by name. Returns a list of matching players with rating, position, club, nation, and IDs.",
  inputSchema: {
    name: z.string().min(1).describe("Player name (or part of it) to search for.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ name }) => {
    try {
      const res = await fetch(`${API}/player/name/${encodeURIComponent(name)}`);
      if (res.status === 404) {
        return { content: [{ type: "text", text: `No player found matching "${name}".` }] };
      }
      if (!res.ok) throw new Error(`Upstream ${res.status}`);
      const raw = await res.json();
      const arr = Array.isArray(raw) ? raw : [raw];
      const players = arr.map((p) => ({
        id: Number(p.ID),
        name: p.Name,
        rating: Number(p.OVR),
        position: p.Position,
        club: p.Team,
        nation: p.Nation,
        league: p.League
      }));
      return {
        content: [{ type: "text", text: JSON.stringify(players, null, 2) }],
        structuredContent: { players }
      };
    } catch (e) {
      return {
        content: [{ type: "text", text: `Search failed: ${e.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/get-player.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
var API2 = "https://api.msmc.cc/api/fc26";
var get_player_default = defineTool2({
  name: "get_player",
  title: "Get player details",
  description: "Get full EA Sports FC 26 player details by ID: overall rating, six main stats (PAC/SHO/PAS/DRI/DEF/PHY), position, foot, skill moves, weak foot, playstyles, club, nation, league.",
  inputSchema: {
    id: z2.number().int().positive().describe("Player ID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ id }) => {
    try {
      const res = await fetch(`${API2}/player/id/${id}`);
      if (!res.ok) throw new Error(`Upstream ${res.status}`);
      const p = await res.json();
      const player = {
        id: Number(p.ID),
        name: p.Name,
        rating: Number(p.OVR),
        position: p.Position,
        altPositions: p["Alternative positions"] ?? [],
        pace: Number(p.PAC),
        shooting: Number(p.SHO),
        passing: Number(p.PAS),
        dribbling: Number(p.DRI),
        defending: Number(p.DEF),
        physical: Number(p.PHY),
        weakFoot: Number(p["Weak foot"]),
        skillMoves: Number(p["Skill moves"]),
        preferredFoot: p["Preferred foot"],
        height: p.Height,
        weight: p.Weight,
        age: Number(p.Age),
        nation: p.Nation,
        league: p.League,
        club: p.Team,
        playStyles: p["play style"] ?? [],
        cardUrl: p.card
      };
      return {
        content: [{ type: "text", text: JSON.stringify(player, null, 2) }],
        structuredContent: { player }
      };
    } catch (e) {
      return {
        content: [{ type: "text", text: `Fetch failed: ${e.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/top-players.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
var API3 = "https://api.msmc.cc/api/fc26";
var top_players_default = defineTool3({
  name: "top_players",
  title: "Top players",
  description: "Get the top N EA Sports FC 26 players by global rank (rank 1 = highest rated).",
  inputSchema: {
    count: z3.number().int().min(1).max(50).describe("How many top players to return (max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ count }) => {
    const ranks = Array.from({ length: count }, (_, i) => i + 1);
    const results = await Promise.all(
      ranks.map(
        (r) => fetch(`${API3}/player/rank/${r}`).then((res) => res.ok ? res.json() : null).catch(() => null)
      )
    );
    const players = results.filter(Boolean).map((p) => ({
      id: Number(p.ID),
      rank: Number(p.Rank),
      name: p.Name,
      rating: Number(p.OVR),
      position: p.Position,
      club: p.Team,
      nation: p.Nation
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(players, null, 2) }],
      structuredContent: { players }
    };
  }
});

// src/lib/mcp/tools/list-favorites.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_favorites_default = defineTool4({
  name: "list_favorites",
  title: "List my favorite players",
  description: "List the signed-in user's favorite FC 26 players saved in futmac.com.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("favorites").select("player_id, player_name, player_rating, player_position, player_club, player_nation, created_at").order("created_at", { ascending: false });
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { favorites: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-favorite.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^4.4.3";
var API4 = "https://api.msmc.cc/api/fc26";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var add_favorite_default = defineTool5({
  name: "add_favorite",
  title: "Add favorite player",
  description: "Add an FC 26 player to the signed-in user's futmac.com favorites.",
  inputSchema: {
    player_id: z4.number().int().positive().describe("Player ID to add.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
  handler: async ({ player_id }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const res = await fetch(`${API4}/player/id/${player_id}`);
    if (!res.ok)
      return { content: [{ type: "text", text: `Player ${player_id} not found` }], isError: true };
    const p = await res.json();
    const { data, error } = await supabaseForUser2(ctx).from("favorites").insert({
      user_id: ctx.getUserId(),
      player_id,
      player_name: p.Name,
      player_rating: Number(p.OVR),
      player_position: p.Position,
      player_club: p.Team,
      player_nation: p.Nation,
      player_avatar_url: p.card ?? null
    }).select().single();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Added ${p.Name} to favorites.` }],
      structuredContent: { favorite: data }
    };
  }
});

// src/lib/mcp/tools/remove-favorite.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var remove_favorite_default = defineTool6({
  name: "remove_favorite",
  title: "Remove favorite player",
  description: "Remove a player from the signed-in user's futmac.com favorites.",
  inputSchema: {
    player_id: z5.number().int().positive().describe("Player ID to remove.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true },
  handler: async ({ player_id }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { error } = await supabaseForUser3(ctx).from("favorites").delete().eq("user_id", ctx.getUserId()).eq("player_id", player_id);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Removed player ${player_id} from favorites.` }] };
  }
});

// src/lib/mcp/index.ts
var projectRef = "betpfgrmxpehxanbcymr";
var mcp_default = defineMcp({
  name: "futmac-mcp",
  title: "futmac.com \u2014 EA FC 26",
  version: "0.1.0",
  instructions: "Tools for the futmac.com EA Sports FC 26 database. Use `search_players` to look up players by name, `get_player` for full stats, `top_players` for the highest-rated players, and `list_favorites` / `add_favorite` / `remove_favorite` to manage the signed-in user's saved players.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_players_default, get_player_default, top_players_default, list_favorites_default, add_favorite_default, remove_favorite_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
